package br.com.portal.service;
import br.com.portal.dto.*; import br.com.portal.exception.*; import br.com.portal.model.*; import br.com.portal.repository.*; import jakarta.servlet.http.HttpSession; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class AlunoService { private final AlunoRepository repo; private final TurmaService turmas; private final TurmaRepository turmaRepo; private final FrequenciaRepository freq; private final AuthService auth; public AlunoService(AlunoRepository r,TurmaService t,TurmaRepository tr,FrequenciaRepository f,AuthService a){repo=r;turmas=t;turmaRepo=tr;freq=f;auth=a;}
 public List<Aluno> listar(Long turma,HttpSession s){turmas.buscar(turma,s);return repo.findByTurmaIdAndStatusOrderByNome(turma,Status.ATIVO);}
 @Transactional public Aluno criar(Long turmaId,AlunoRequest req,HttpSession s){Turma t=turmas.buscar(turmaId,s);String m=req.matricula().trim().toUpperCase();if(repo.existsByMatriculaIgnoreCase(m))throw new RegraNegocioException("A matrícula já está cadastrada.");Aluno a=new Aluno();a.setNome(req.nome().trim());a.setMatricula(m);a.setDataNascimento(req.dataNascimento());a.setTurma(t);return repo.save(a);}
 @Transactional public Aluno atualizar(Long id,AlunoRequest req,HttpSession s){Aluno a=repo.findByIdAndTurmaInstrutorId(id,auth.usuarioAtual(s).getId()).orElseThrow(()->new RecursoNaoEncontradoException("Aluno não encontrado."));String m=req.matricula().trim().toUpperCase();if(repo.existsByMatriculaIgnoreCaseAndIdNot(m,id))throw new RegraNegocioException("A matrícula já está cadastrada por outro aluno.");a.setNome(req.nome().trim());a.setMatricula(m);a.setDataNascimento(req.dataNascimento());return repo.save(a);}
 public Aluno buscar(Long id,HttpSession s){return repo.findByIdAndTurmaInstrutorId(id,auth.usuarioAtual(s).getId()).orElseThrow(()->new RecursoNaoEncontradoException("Aluno não encontrado."));}
 @Transactional public void excluir(Long id,HttpSession s){Aluno a=buscar(id,s);if(freq.existsByAlunoId(id))throw new RegraNegocioException("Aluno possui histórico de frequência e não pode ser excluído.");a.setStatus(Status.INATIVO);repo.save(a);}
}
