package br.com.portal.service;
import br.com.portal.dto.*; import br.com.portal.exception.*; import br.com.portal.model.*; import br.com.portal.repository.*; import jakarta.servlet.http.HttpSession; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import java.util.stream.Collectors;
@Service public class FrequenciaService {
 private final UnidadeCurricularRepository ucRepo; private final AlunoRepository alunoRepo; private final AulaRepository aulaRepo; private final FrequenciaRepository freqRepo; private final TurmaService turmas; private final AuthService auth;
 public FrequenciaService(UnidadeCurricularRepository u,AlunoRepository a,AulaRepository ar,FrequenciaRepository f,TurmaService t,AuthService x){ucRepo=u;alunoRepo=a;aulaRepo=ar;freqRepo=f;turmas=t;auth=x;}
 @Transactional public Aula salvar(AulaRequest req,HttpSession s){Long instrutorId=auth.usuarioAtual(s).getId(); UnidadeCurricular uc=ucRepo.findByIdAndTurmaInstrutorId(req.ucId(),instrutorId).orElseThrow(()->new RecursoNaoEncontradoException("Unidade curricular não encontrada.")); // ownership validated below
 if(req.data().isAfter(LocalDate.now()))throw new RegraNegocioException("Não é permitido registrar uma aula futura.");int ultimo=aulaRepo.countByUnidadeCurricularId(uc.getId());if(req.numeroAula()!=ultimo+1)throw new RegraNegocioException("A próxima aula deve ser a de número "+(ultimo+1)+".");if(req.numeroAula()>uc.getTotalAulas())throw new RegraNegocioException("O número da aula ultrapassa o total previsto para a UC.");
 List<Aluno> ativos=alunoRepo.findByTurmaIdAndStatusOrderByNome(uc.getTurma().getId(),Status.ATIVO);Map<Long,PresencaRequest> mapa=req.presencas().stream().collect(Collectors.toMap(PresencaRequest::alunoId,x->x,(a,b)->{throw new RegraNegocioException("Aluno duplicado na chamada.");}));if(mapa.size()!=ativos.size()||!mapa.keySet().containsAll(ativos.stream().map(Aluno::getId).toList()))throw new RegraNegocioException("A chamada deve conter todos os alunos ativos da turma.");
 Aula aula=new Aula();aula.setUnidadeCurricular(uc);aula.setNumero(req.numeroAula());aula.setData(req.data());aula.setObservacao(req.observacao());aula=aulaRepo.save(aula);
 for(Aluno a:ativos){PresencaRequest p=mapa.get(a.getId());Frequencia f=new Frequencia();f.setAula(aula);f.setAluno(a);f.setPresente(Boolean.TRUE.equals(p.presente()));freqRepo.save(f);}return aula; }
 public List<AulaResponse> aulas(Long turmaId,Long ucId,HttpSession s){turmas.buscar(turmaId,s);UnidadeCurricular uc=ucRepo.findById(ucId).orElseThrow(()->new RecursoNaoEncontradoException("UC não encontrada."));if(!uc.getTurma().getId().equals(turmaId))throw new RegraNegocioException("UC não pertence à turma informada.");return aulaRepo.findByUnidadeCurricularIdOrderByNumero(ucId).stream().map(a->new AulaResponse(a.getId(),a.getNumero(),a.getData(),a.getObservacao())).toList();}
 public RelatorioResponse relatorio(Long turmaId,Long ucId,HttpSession s){turmas.buscar(turmaId,s);UnidadeCurricular uc=ucRepo.findById(ucId).orElseThrow(()->new RecursoNaoEncontradoException("UC não encontrada."));if(!uc.getTurma().getId().equals(turmaId))throw new RegraNegocioException("UC não pertence à turma informada.");int total=aulaRepo.countByUnidadeCurricularId(ucId);List<AlunoFrequenciaResponse> lista=alunoRepo.findByTurmaIdAndStatusOrderByNome(turmaId,Status.ATIVO).stream().map(a->calc(a,uc,total)).toList();return new RelatorioResponse(turmaId,ucId,uc.getNome(),total,lista,lista.stream().filter(AlunoFrequenciaResponse::alerta).toList());}
 private AlunoFrequenciaResponse calc(Aluno a,UnidadeCurricular uc,int total){long n=freqRepo.countByAlunoAndUc(a.getId(),uc.getId()),p=freqRepo.countPresentesByAlunoAndUc(a.getId(),uc.getId());double pct=n==0?100.0:(p*100.0/n);List<Frequencia> fs=freqRepo.findByUc(uc.getId()).stream().filter(f->f.getAluno().getId().equals(a.getId())).sorted(Comparator.comparing(f->f.getAula().getNumero())).toList();boolean seq=false;for(int i=1;i<fs.size();i++){Frequencia atual=fs.get(i),anterior=fs.get(i-1);if(atual.getAula().getNumero()==anterior.getAula().getNumero()+1&&!atual.isPresente()&&!anterior.isPresente()){seq=true;break;}}boolean alerta=pct<75;String msg=alerta?String.format("Frequência de %.1f%%, abaixo do mínimo de 75%%.",pct):seq?"Aluno possui faltas consecutivas.":"";return new AlunoFrequenciaResponse(a.getId(),a.getNome(),a.getMatricula(),n,p,Math.round(pct*10)/10.0,alerta,seq,msg);}
}
