package br.com.portal.service;
import br.com.portal.dto.*; import br.com.portal.exception.*; import br.com.portal.model.*; import br.com.portal.repository.*; import jakarta.servlet.http.HttpSession; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class UCService { private final UnidadeCurricularRepository repo; private final TurmaService turmas; private final AulaRepository aulas; private final FrequenciaRepository freq; private final AuthService auth; public UCService(UnidadeCurricularRepository r,TurmaService t,AulaRepository a,FrequenciaRepository f,AuthService x){repo=r;turmas=t;aulas=a;freq=f;auth=x;}
 public List<UnidadeCurricular> listar(Long turma,HttpSession s){turmas.buscar(turma,s);return repo.findByTurmaIdAndStatusOrderByNome(turma,Status.ATIVO);}
 @Transactional public UnidadeCurricular criar(Long turma,UCRequest req,HttpSession s){Turma t=turmas.buscar(turma,s);String n=req.nome().trim();if(repo.existsByTurmaIdAndNomeIgnoreCase(turma,n))throw new RegraNegocioException("Esta unidade curricular já existe na turma.");UnidadeCurricular u=new UnidadeCurricular();u.setNome(n);u.setTotalAulas(req.totalAulas());u.setTurma(t);return repo.save(u);}
 public UnidadeCurricular buscar(Long id,HttpSession s){return repo.findByIdAndTurmaInstrutorId(id,auth.usuarioAtual(s).getId()).orElseThrow(()->new RecursoNaoEncontradoException("Unidade curricular não encontrada."));}
 @Transactional public UnidadeCurricular atualizar(Long id,UCRequest req,HttpSession s){UnidadeCurricular u=buscar(id,s);if(repo.existsByTurmaIdAndNomeIgnoreCaseAndIdNot(u.getTurma().getId(),req.nome().trim(),id))throw new RegraNegocioException("Já existe outra unidade curricular com esse nome.");int registradas=aulas.countByUnidadeCurricularId(id);if(req.totalAulas()<registradas)throw new RegraNegocioException("O total de aulas não pode ser menor que as aulas já registradas.");u.setNome(req.nome().trim());u.setTotalAulas(req.totalAulas());return repo.save(u);}
 @Transactional public void excluir(Long id,HttpSession s){UnidadeCurricular u=buscar(id,s);if(aulas.countByUnidadeCurricularId(id)>0||freq.existsByAulaUnidadeCurricularId(id))throw new RegraNegocioException("A unidade curricular possui histórico e não pode ser excluída.");u.setStatus(Status.INATIVO);repo.save(u);}
}
